### PR TITLE
Fix for fnc_magInit

### PR DESCRIPTION
**Pull request by Torndeco**
Fix for Magazine Ammo Count

### CODE REVIEW

**Comment by robalo** [comment]
Can you please add more detail about this fix ? Thanks !

**Comment by Torndeco** [comment]
Find is case sensitive

For example 
If ammo classname is
HLC_fooo
But in class nia_magSwitch you have it called
hlc_fooo

You find check will fail, because they have different case.
The ammo won't get re-added to the player

**Comment by Torndeco** [comment]
This fix is just to pass the ammo count which is wanted by Niarms_fnc_magSwitch.

**Comment by robalo** [comment]
I got that one this is about ammo count, is it for preventing replacing with full mag at init ?

**Comment by robalo** [comment]
k, thx

**Comment by robalo** [comment]
Instead of looping all gear, I believe you can get ammo count faster with
_unit ammo (currentMuzzle _unit)

**Comment by Torndeco** [comment]
Yeah you are right, made the changes

**Pull request merged**
